### ISSUE TITLE
UAC Prompt not working

### ISSUE THREAD

**Issue by th3030** [MeisApps/pcbu-desktop#11]
For this bug to occur. You have to be logged in with a limited (non admin) account. Run a program as administrator. In the UAC prompt select more options. You see PC Bio Unlock as a option which starts with the text "Initializing..." and no account name. Clicking on the PC Bio Unlock does connect to the phone and the phone does prompt to unlock. However succesfully unlocking via prompt still causes the error message "The user or password is incorrect." Despite this working in Windows Logon. The phone does however recognize which account is being chosen (Not visible in the UAC prompt with PC Bio Unlock selected).

**Comment by MeisApps** [comment]
You're right, with a non admin account it does not work correctly. I've looked into it and the correct user is passed to Windows, weird. I'll fix it when I have more time to research this.

**Comment by th3030** [comment]
It's indeed very strange.
So far the only use case I know for UAC password prompt is when it's ran from a limited account.

**Comment by th3030** [comment]
Is there any status update about this issue?

**Comment by MeisApps** [comment]
Fixed with the latest commit. I'll release an update later.

**Comment by th3030** [comment]
I tested the newest pre-release and can confirm that it does work!

P.S. A small issue for now but is it possible to show the username in the PC Bio Unlock option instead of "Initializing..." and no account name?

**Comment by th3030** [comment]
I'll close this issue as the main problem of the UAC not working is indeed fixed

**Comment by MeisApps** [comment]
Great. I'll release another update soon.
Showing the username is definitely possible, but this issue has low priority for now.
