### ISSUE TITLE
Works with log `pamsystemdhome(polkit-1:account)`, does not work with log `pamsystemdhome(polkit-1:auth)`

### ISSUE THREAD

**Issue by look997** [MeisApps/pcbu-desktop#12]
I'm testing PC Bio Unlock, which allows you to use the fingerprint reader from your phone instead of the password on your PC.
 Then maybe I'll buy a USB fingerprint reader.

But it doesn't always work, the logs showed that it works with `account`:
`polkit-agent-helper-1[114263]: pamsystemdhome(polkit-1:account): New sd-bus connection (system-bus-pam-systemd-home-114263) opened.`

And with `auth` it doesn't work:
`polkit-agent-helper-1[114018]: pamsystemdhome(polkit-1:auth): New sd-bus connection (system-bus-pam-systemd-home-114018) opened.`

I invoke the first one, e.g. with "Edit as admin" from Nautilus, and the second one with any systemctl enable x.
It also works with GDM.  with TTY1 it also fired once.

When it doesn't work, you see the words `Connecting to phone...`, but immediately a regular password entry field appears.  Sometimes the phone even blinks, but there is no question about the fingerprint.

How to make it work both here and here?  Or that it should always be called with auth?

I have the default configuration, just like PC Bio Unlock does.

`/etc/pam.d/polkit-1`

```
#%PAM-1.0
auth sufficient pam_pcbiounlock.so
## Generated by PC Bio Unlock

auth include system-auth
account include system-auth
password include system-auth
session include system-auth
```

Using `sudo` doesn't work (log `pam_systemd_home(sudo:auth): New sd-bus connection (system-bus-pam-systemd-home-166429) opened.`), and I haven't found a situation where it would work, I guess that with TTY1, when I logged in without GDM, but this is uncertain.

I obtained the logs by adding debug `auth sufficient pam_pcbiounlock.so debug` in the PAM files.

BTW Why does `su` not try to connect to the phone at all?

**Comment by MeisApps** [comment]
Hi, normally it should work with account and auth, but that looks more like a connection issue. Have you tried both TCP and Bluetooth? And which Linux distribution are you using?

You can make `su` work if you edit the PAM config manually, but I would not recommend it, since it's good to have something to fall back on if things go wrong.

**Comment by look997** [comment]
Arch Linux with Cinnamon and GNOME Apps.

I haven't tried Bluetooth because I don't have Bluetooth on my PC (it's a desktop computer).

**Comment by MeisApps** [comment]
Please try out the new pre-release: https://github.com/MeisApps/pcbu-desktop/releases/tag/v2.0.3
If that doesn't help, I would need the logs you can see in the desktop app.

**Comment by look997** [comment]
It already works with the new version.  :D
Thanks.
