### ISSUE TITLE
Error during pairing

### ISSUE THREAD

**Issue by Huozheng-Li** [MeisApps/pcbu-desktop#13]
To whom it may concern,
During the pairing process, the software on my mobile phone showed an error as shown below:
![2b40bb3dc99cabd37fdacf21b510729](https://github.com/user-attachments/assets/848e483a-5b13-41e5-b2c1-67c9863b3ed8)

It would be sincerely appreciated if you could tell me how to solve this problem and successfully match. And sincerely thank you for developing such a good software which largely improved security while unlocking.

Warm regards,
Huozheng Li

**Comment by MeisApps** [comment]
Hello,
the error seems to happen on the PC. Please provide me with the logs of the desktop app, so I can investigate further. Are you using Windows or Linux?

Best regards,
Meis Apps

**Comment by CaptainMusX** [comment]
Hello,
I encountered the same issue. Attached is a screenshot of my log details.
![image](https://github.com/user-attachments/assets/b5ff7a9b-e636-46c5-a7a8-8dde4568777c)
