### ISSUE TITLE
Unlock via VPN

### ISSUE THREAD

**Issue by ymickler** [MeisApps/pcbu-desktop#14]
Maybe it is more a question if this is possible.

I would like to login from mobile date via VPN in my home network and in the normal way inside my home network.
My device is connected via fritz box VPN and in the router the VPN Network has a defined IP.

Is there a way to pair my smartphone and my pc twice?
First one is already set up via normal network connection, second one via VPN in my home network on mobile data?

**Comment by MeisApps** [comment]
Pairing twice with the same connection method is not possible as is. You could modify the code and make pairing ID's random to get it working in theory. Haven't tried something like this.
