### ISSUE TITLE
Error generating QR Codes

### ISSUE THREAD

**Issue by Jonatas-Goncalves** [MeisApps/pcbu-desktop#15]
After installing the PAM module (which occurs without errors), when I go to the pairing section, when I get to the qrcode screen nothing appears and it stays stuck on this black screen.
I am using openSUSE Tumbleweed.

![image](https://github.com/user-attachments/assets/06117bb6-fb22-4bc9-8cb9-f62360dc09c3)

![image](https://github.com/user-attachments/assets/84e165f8-0556-48a4-8aa7-06711cc98725)

**Comment by MeisApps** [comment]
Please try the latest pre-release: https://github.com/MeisApps/pcbu-desktop/releases/tag/v2.0.6
The issue was also present on Arch Linux.

**Comment by Jonatas-Goncalves** [comment]
Same thing...

![image](https://github.com/user-attachments/assets/4a7d9e6a-82bb-4d9d-bea1-01c360e9698d)

Is this error caused by some dependency?
If you need help with other tests, please let me know, I'll be happy to help.

**Comment by Jonatas-Goncalves** [comment]
It worked perfectly!

![image](https://github.com/user-attachments/assets/26e09dbb-7f4d-419e-8ed3-d36c91130e80)

I forgot to thank you for this incredible project.
You did an amazing job.
If you need me to perform new tests, just let me know, I will be happy to help.

Thank you very much!

**Comment by MeisApps** [comment]
Thank you! I'm glad you like it.
The update is now released.
I don't need other tests right now, but a review on Google Play is always appreciated.
