### ISSUE TITLE
Feature Request: Ability to choose domain accounts

### ISSUE THREAD

**Issue by Redn2000** [MeisApps/pcbu-desktop#16]
Would it be possible to implement the option to allow the user to, instead of choosing from a local account, instead specify the domain of the account? 
For example: Instead of <my-computer-name>\<local_account> it could be <enter_domain_name>\<account_name>
This would be helpful for users that log in through Active Directory.

**Comment by th3030** [comment]
It's now possible to manually write a username in the pairing device section.

**Comment by MeisApps** [comment]
With the latest version, you can now specify the domain and account name manually.
This should make it possible to log into an AD account.
