### ISSUE TITLE
Feature Request: Show the usernames on the UAC Prompt

### ISSUE THREAD

**Issue by th3030** [MeisApps/pcbu-desktop#17]
As I wrote earlier in the previous issue [#11](https://github.com/MeisApps/pcbu-desktop/issues/11#issuecomment-2267540604) The usernames are not shown in the PC Bio Unlock credential provider, and is shown as "initializing...". Would be more convenient if it were there.

**Comment by MeisApps** [comment]
Implemented in https://github.com/MeisApps/pcbu-desktop/commit/7f77e57b1c9bd5dec57e1c4d285539095798157c

**Comment by th3030** [comment]
Confirmed it works! Closing this issue!
