### ISSUE TITLE
Bug: Incorrect password on Windows Login Screen when a password is pre-typed.

### ISSUE THREAD

**Issue by th3030** [MeisApps/pcbu-desktop#18]
To reproduce this issue, follow these steps:

    Enter any text in the Windows password field.
    Wait for the PC Bio Unlock app on your phone to prompt for unlocking.
    Successfully unlock your PC using the phone prompt.

After unlocking, you'll notice that the login fails because the password entered is now invalid. This suggests that the app is appending the password over the existing password in the field, with the one from your phone, causing a conflict.

**Comment by MeisApps** [comment]
Fixed in https://github.com/MeisApps/pcbu-desktop/commit/e8c53cfc29561e586564f51106dbfee231ee662a

**Comment by th3030** [comment]
Confirmed it works! Closing this issue!
