### ISSUE TITLE
Custom unlock server port is ignored

### ISSUE THREAD

**Issue by lmgarret** [MeisApps/pcbu-desktop#20]
Hello! I believe the `Unlock server port` setting is ignored by this LOC:
https://github.com/MeisApps/pcbu-desktop/blob/9c6f1887a4faf4c4051148d862b4367af65dc56a/common/src/handler/UnlockHandler.cpp#L39

On the server side, changing to port 43298 does indeed work even if  `Unlock server port` is set to 43296

**Comment by MeisApps** [comment]
Hi, the `Unlock server port` setting is for an upcoming pairing method. Currently, it's not possible to change the server port on Android's side.
