### ISSUE TITLE
Logon tile often disappears after cold boot

### ISSUE THREAD

**Issue by lmgarret** [MeisApps/pcbu-desktop#22]
Hi! I've noticed that the PCBU logon tile often disappears when cold booting. My PC is connected to a smartplug, shutting down after the PC shuts down. So literally cold booting from no power!

The service logs gives me this:
```log
[2024-11-14 15:44:34.167] Logger init.
[2024-11-14 15:44:34.242] Could not find any paired user.
[2024-11-14 15:46:24.919] Logger destroy.
```
but I do have a paired user, which I can use to unlock when locking my session (win+L). And I still get this error after a cold boot.

The only (temporay) fix I've found is to remove the existing paired user from the desktop app, and re-pair the account again. But that only works for some time after which the tile disappears and the same error is logged again.

I followed [this issue ](https://github.com/MeisApps/pcbu-desktop/issues/5) but that does not fix it unfortunately.

Any idea of what could be wrong here? Thanks

**Comment by MeisApps** [comment]
Hi,
please try this pre-release: https://github.com/MeisApps/pcbu-desktop/releases/tag/v2.0.9
When not cold booting, Windows returns the domain name of a user in uppercase. For some reason, it doesn't when you do a cold boot sometimes. I've made the check case-insensitive.

**Comment by lmgarret** [comment]
Nice quick fix, the logon tile is back indeed, thanks! I'm using my [pip package](https://github.com/lmgarret/py-pcbu) to unlock automatically, so I'll have to change matching logic there to also ignore the case, but it looks all good now. Pretty weird behavior from Windows tbf..
