### ISSUE TITLE
bluetooth device is not trusted after rebooting bluetooth

### ISSUE THREAD

**Issue by adriadam10** [MeisApps/pcbu-desktop#3]
I have noticed that if I reboot the computer or the Bluetooth dongle, and then try to log in, it resets the connection between the phone and the computer, prompting for the PIN if I try to connect them manually.
In the phone the computer disappears from known devices.

I have tried to test this without using the program and it didn't delete the phone connection.

OS: ArchLinux with KDE

**Comment by MeisApps** [comment]
Sorry it took so long to get to this issue. I tried to reproduce it, but couldn't.
Does this still happen in the latest version?
