### ISSUE TITLE
Question: How to enable the pc unlock option on login screen per default?

### ISSUE THREAD

**Issue by ymickler** [MeisApps/pcbu-desktop#5]
Not quite sure if that has something todo with the previous issue I've opened but my pc uses the windows hello pin per default and I need to manually switch to the pc unlock service.
I've tried to uninstall and reinstall the service with an older version of the pc unlock app which sometimes fixed it.
Is there any trick to use the pc unlock on login screen per default?

**Comment by MeisApps** [comment]
Normally, the credential provider last used will be set to the default by Windows.
Do you have group policies set or is your PC managed by an organization?
You could try setting the default manually through the registry, like in [this guide](https://www.technine.be/2020/05/16/how-to-set-default-sign-in-option-in-windows-10/).
Set the GUID to {74A23DE2-B81D-46EC-E129-CD32507ED716} and PC Bio Unlock should be the default.

**Comment by ymickler** [comment]
@MeisApps Thanks, I got it working with the guide you provided
