### ISSUE TITLE
Unlocking computer remotely does not work

### ISSUE THREAD

**Issue by adrienrichmond** [MeisApps/pcbu-desktop#7]
Hey! When I try to unlock my PC remotely with the application, this is not possible, I do not receive the notification on my phone. 

However, locally this works.. Thank you!

**Comment by MeisApps** [comment]
Hi, the PC and phone need to establish a direct connection to each other. If your PC is not nearby or in your local network, unlocking is currently not possible. I have an idea on how to make this work in the future, but I'll have to check if the idea is feasible, and it would take a lot of time.
