### ISSUE TITLE
Unable to pair on new desktop app (Linux)

### ISSUE THREAD

**Issue by davidmartos96** [MeisApps/pcbu-desktop#9]
Hello!
The new desktop app is looking nice.

I have an issue setting it up on Linux though, and the previous Java based version was pairing fine.
On the new app, after setting up the server IP address manually, when I try to pair an Android device, the mobile app will complain with "Failed to connect to the PC. Please try setting you IP Address in the desktop app settings and make sure your firewall is configured correctly".

When starting the pairing flow I see the following logs, but the desktop settings look just fine

![image](https://github.com/MeisApps/pcbu-desktop/assets/22084723/53c25371-262b-4919-be07-4f2130048276)

```
[2024-07-04 10:51:11.288] Invalid server IP settings.
[2024-07-04 10:51:11.288] Pairing server started.
[2024-07-04 10:51:11.290] Invalid server IP settings.
```

I've never experienced firewall or connection issues with AppImage based apps.

Not sure if related, but another thing I'm experiencing when running the desktop app is that it will hang for several seconds before displaying the UI with the following logs. The QT log is the one that displays after several seconds of freeze.

```
[2024-07-04 10:41:09.822] Logger init.
qt.qpa.plugin: Could not find the Qt platform plugin "wayland" in ""
[2024-07-04 10:41:10.205] Failed checking for updates: SSL server verification failed
qt.accessibility.atspi: Error in contacting registry: "org.freedesktop.DBus.Error.NoReply" "Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken."
```

Thank you for your work, keep it up!
 
Desktop app version 2.0.1

**Comment by MeisApps** [comment]
Oops, I wasn't setting the IP address correctly if it's manually entered. Will be fixed in the next update.
Do you mean the freeze happens only with the logs window? If not, please tell me which distro you're using and your desktop environment.

**Comment by davidmartos96** [comment]
@MeisApps I see.

The freeze happens every time I open the app. It didn't the first time I opened it though.

My distro is Fedora 39 with GNOME

**Comment by davidmartos96** [comment]
@MeisApps Not related to the logs window, because the logs I'm seeing them by launching the AppImage from a terminal

**Comment by MeisApps** [comment]
Please try running the AppImage with the following environment variable: `NO_AT_BRIDGE=1 ./PCBioUnlock.AppImage`.
I tried to reproduce the freezing on your distro within a VM, but it worked fine there. It looks like the `qt.accessibility.atspi` line causes this.

**Comment by davidmartos96** [comment]
@MeisApps With that env var it doesn't freeze

**Comment by MeisApps** [comment]
Thanks for testing. Just one more thing, could you please try installing/reinstalling the package `at-spi2-core`? The issue might get resolved through that. The env var is more of a workaround by simply disabling accessibility.

**Comment by davidmartos96** [comment]
@MeisApps `dnf reinstall at-spi2-core` fixed the freeze. Thanks!

**Comment by MeisApps** [comment]
Fixed in the latest version.

**Comment by davidmartos96** [comment]
Thank you!
